### ISSUE TITLE
Remove main folder at upgrade - Good practice ?

### ISSUE THREAD

**Issue by Josue-T** [YunoHost-Apps/friendica_ynh#8]
I discovered [in the upgrade script in line 45](https://github.com/YunoHost-Apps/friendica_ynh/blob/master/scripts/upgrade#L45) at each upgrade we remove everything. Is it a really a good practice because we have some which is useful (by example in `$finalpath/proxy` and `$finalphat/photo` ).

**Comment by anmol26s** [comment]
See this: https://github.com/friendica/friendica/issues/3589#issuecomment-317039372
and the upgrade procedure described here https://github.com/friendica/friendica/releases.
If you think these files/folders are important  and is breaking something then please advise the folders to be backed up. Otherwise removing this line should not break anything,I guess. I did this clean upgrade as advised in the upgrade procedure for Friendica.

**Comment by Josue-T** [comment]
Yes, but as I understand the  `$finalpath/proxy` and `$finalphat/photo` is not really necessary but probably something more like a cache. But as I tested friendica is really heavy so it could be good to not force friendica to remake the cache at each upgrade. But it stay my point of view.

**Comment by anmol26s** [comment]
Thanks for referring the cache issue. I have made you admin of the project. I personally have more inclination towards Hubzilla app. So I never used this package but kept it updating because I thought some day I will install both the project together and do deep comparison. That day never came. Now that you are using the this app and have the skill to improve it, I invite you to improve this app. I have subscribed to Friendica support form to get there updates but I might miss them and you are in better position to keep a check on them. Moreover apps level has to be pulled up from 4 to 7. So you are in better position to see the issues of the app.

I have started testing branch in which I have removed **ynh_secure_remove "$final_path"**, you can upgrade and if everything works you can merge into master.
